/**
 * NRF NFDiscovery Service
 * NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string/classification.hpp>
#include "DiscNFInstancesStoreApi.h"
#include "Helpers.h"
#include "nrf_config.hpp"
#include "logger.hpp"

extern std::unique_ptr<oai::config::nrf::nrf_config> nrf_cfg;

namespace oai {
namespace nrf {
namespace api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;

DiscNFInstancesStoreApi::DiscNFInstancesStoreApi(
    std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
}

void DiscNFInstancesStoreApi::init() {
  setupRoutes();
}

void DiscNFInstancesStoreApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router,
      base + nrf_cfg->local().get_sbi().get_api_version() + "/nf-instances",
      Routes::bind(
          &DiscNFInstancesStoreApi::search_nf_instances_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &DiscNFInstancesStoreApi::nf_instances_store_api_default_handler, this));
}

void DiscNFInstancesStoreApi::search_nf_instances_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  // Getting the query params
  // TODO Stefan: We should use the model values everywhere and then to_json,
  // e.g. NFType, so we can use the enum and we are typesafe
  auto targetNfTypeQuery = request.query().get("target-nf-type");
  std::optional<std::string> targetNfType;
  if (targetNfTypeQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(targetNfTypeQuery.value(), valueQuery_instance)) {
      targetNfType = valueQuery_instance;
    }
  }
  auto requesterNfTypeQuery = request.query().get("requester-nf-type");
  std::optional<std::string> requesterNfType;
  if (requesterNfTypeQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(requesterNfTypeQuery.value(), valueQuery_instance)) {
      requesterNfType = valueQuery_instance;
    }
  }
  auto requesterNfInstanceIdQuery =
      request.query().get("requester-nf-instance-id");
  std::optional<std::string> requesterNfInstanceId;
  if (requesterNfInstanceIdQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(
            requesterNfInstanceIdQuery.value(), valueQuery_instance)) {
      requesterNfInstanceId = valueQuery_instance;
    }
  }
  std::optional<std::vector<ServiceName>> serviceNames =
      model_from_query_string<std::vector<ServiceName>>(
          request, "service-names", true);

  auto requesterNfInstanceFqdnQuery =
      request.query().get("requester-nf-instance-fqdn");
  std::optional<std::string> requesterNfInstanceFqdn;
  if (requesterNfInstanceFqdnQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(
            requesterNfInstanceFqdnQuery.value(), valueQuery_instance)) {
      requesterNfInstanceFqdn = valueQuery_instance;
    }
  }
  std::optional<std::vector<PlmnId>> targetPlmnList =
      model_from_query_string<std::vector<PlmnId>>(
          request, "target-plmn-list", true);

  std::optional<std::vector<PlmnId>> requesterPlmnList =
      model_from_query_string<std::vector<PlmnId>>(
          request, "requester-plmn-list", true);

  auto targetNfInstanceIdQuery = request.query().get("target-nf-instance-id");
  std::optional<std::string> targetNfInstanceId;
  if (targetNfInstanceIdQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(targetNfInstanceIdQuery.value(), valueQuery_instance)) {
      targetNfInstanceId = valueQuery_instance;
    }
  }
  auto targetNfFqdnQuery = request.query().get("target-nf-fqdn");
  std::optional<std::string> targetNfFqdn;
  if (targetNfFqdnQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(targetNfFqdnQuery.value(), valueQuery_instance)) {
      targetNfFqdn = valueQuery_instance;
    }
  }
  auto hnrfUriQuery = request.query().get("hnrf-uri");
  std::optional<std::string> hnrfUri;
  if (hnrfUriQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(hnrfUriQuery.value(), valueQuery_instance)) {
      hnrfUri = valueQuery_instance;
    }
  }

  std::optional<std::vector<Snssai>> snssais =
      model_from_query_string<std::vector<Snssai>>(request, "snssais", true);
  std::optional<std::vector<Snssai>> requesterSnssais =
      model_from_query_string<std::vector<Snssai>>(
          request, "requester-snssais", true);
  std::optional<std::vector<PlmnSnssai>> plmnSpecificSnssaiList =
      model_from_query_string<std::vector<PlmnSnssai>>(
          request, "plmn-specific-snssai-list", true);

  auto dnnQuery = request.query().get("dnn");
  std::optional<std::string> dnn;
  if (dnnQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(dnnQuery.value(), valueQuery_instance)) {
      dnn = valueQuery_instance;
    }
  }
  auto nsiListQuery = request.query().get("nsi-list");
  std::optional<std::vector<std::string>> nsiList;
  if (nsiListQuery.has_value()) {
    std::vector<std::string> valueQuery_instance;
    if (fromStringValue(nsiListQuery.value(), valueQuery_instance)) {
      nsiList = valueQuery_instance;
    }
  }
  auto smfServingAreaQuery = request.query().get("smf-serving-area");
  std::optional<std::string> smfServingArea;
  if (smfServingAreaQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(smfServingAreaQuery.value(), valueQuery_instance)) {
      smfServingArea = valueQuery_instance;
    }
  }
  std::optional<Tai> tai = model_from_query_string<Tai>(request, "tai");
  auto amfRegionIdQuery  = request.query().get("amf-region-id");
  std::optional<std::string> amfRegionId;
  if (amfRegionIdQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(amfRegionIdQuery.value(), valueQuery_instance)) {
      amfRegionId = valueQuery_instance;
    }
  }
  auto amfSetIdQuery = request.query().get("amf-set-id");
  std::optional<std::string> amfSetId;
  if (amfSetIdQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(amfSetIdQuery.value(), valueQuery_instance)) {
      amfSetId = valueQuery_instance;
    }
  }
  std::optional<Guami> guami = model_from_query_string<Guami>(request, "guami");
  auto supiQuery             = request.query().get("supi");
  std::optional<std::string> supi;
  if (supiQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(supiQuery.value(), valueQuery_instance)) {
      supi = valueQuery_instance;
    }
  }
  auto ueIpv4AddressQuery = request.query().get("ue-ipv4-address");
  std::optional<std::string> ueIpv4Address;
  if (ueIpv4AddressQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(ueIpv4AddressQuery.value(), valueQuery_instance)) {
      ueIpv4Address = valueQuery_instance;
    }
  }
  auto ipDomainQuery = request.query().get("ip-domain");
  std::optional<std::string> ipDomain;
  if (ipDomainQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(ipDomainQuery.value(), valueQuery_instance)) {
      ipDomain = valueQuery_instance;
    }
  }
  std::optional<Ipv6Prefix> ueIpv6Prefix =
      model_from_query_string<Ipv6Prefix>(request, "ue-ipv6-prefix");

  auto pgwIndQuery = request.query().get("pgw-ind");
  std::optional<bool> pgwInd;
  if (pgwIndQuery.has_value()) {
    bool valueQuery_instance;
    if (fromStringValue(pgwIndQuery.value(), valueQuery_instance)) {
      pgwInd = valueQuery_instance;
    }
  }
  auto pgwQuery = request.query().get("pgw");
  std::optional<std::string> pgw;
  if (pgwQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(pgwQuery.value(), valueQuery_instance)) {
      pgw = valueQuery_instance;
    }
  }
  auto gpsiQuery = request.query().get("gpsi");
  std::optional<std::string> gpsi;
  if (gpsiQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(gpsiQuery.value(), valueQuery_instance)) {
      gpsi = valueQuery_instance;
    }
  }
  auto externalGroupIdentityQuery =
      request.query().get("external-group-identity");
  std::optional<std::string> externalGroupIdentity;
  if (externalGroupIdentityQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(
            externalGroupIdentityQuery.value(), valueQuery_instance)) {
      externalGroupIdentity = valueQuery_instance;
    }
  }
  std::optional<DataSetId> dataSet =
      model_from_query_string<DataSetId>(request, "data-set");

  auto routingIndicatorQuery = request.query().get("routing-indicator");
  std::optional<std::string> routingIndicator;
  if (routingIndicatorQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(routingIndicatorQuery.value(), valueQuery_instance)) {
      routingIndicator = valueQuery_instance;
    }
  }
  auto groupIdListQuery = request.query().get("group-id-list");
  std::optional<std::vector<std::string>> groupIdList;
  if (groupIdListQuery.has_value()) {
    std::vector<std::string> valueQuery_instance;
    if (fromStringValue(groupIdListQuery.value(), valueQuery_instance)) {
      groupIdList = valueQuery_instance;
    }
  }
  auto dnaiListQuery = request.query().get("dnai-list");
  std::optional<std::vector<std::string>> dnaiList;
  if (dnaiListQuery.has_value()) {
    std::vector<std::string> valueQuery_instance;
    if (fromStringValue(dnaiListQuery.value(), valueQuery_instance)) {
      dnaiList = valueQuery_instance;
    }
  }
  std::optional<std::vector<PduSessionType>> pduSessionTypes =
      model_from_query_string<std::vector<PduSessionType>>(
          request, "pdu-session-types", true);

  std::optional<std::vector<EventId>> eventIdList =
      model_from_query_string<std::vector<EventId>>(
          request, "event-id-list", true);

  std::optional<std::vector<NwdafEvent>> nwdafEventList =
      model_from_query_string<std::vector<NwdafEvent>>(
          request, "nwdaf-event-list", true);

  auto supportedFeaturesQuery = request.query().get("supported-features");
  std::optional<std::string> supportedFeatures;
  if (supportedFeaturesQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(supportedFeaturesQuery.value(), valueQuery_instance)) {
      supportedFeatures = valueQuery_instance;
    }
  }
  auto upfIwkEpsIndQuery = request.query().get("upf-iwk-eps-ind");
  std::optional<bool> upfIwkEpsInd;
  if (upfIwkEpsIndQuery.has_value()) {
    bool valueQuery_instance;
    if (fromStringValue(upfIwkEpsIndQuery.value(), valueQuery_instance)) {
      upfIwkEpsInd = valueQuery_instance;
    }
  }
  std::optional<PlmnId> chfSupportedPlmn =
      model_from_query_string<PlmnId>(request, "chf-supported-plmn");

  auto preferredLocalityQuery = request.query().get("preferred-locality");
  std::optional<std::string> preferredLocality;
  if (preferredLocalityQuery.has_value()) {
    std::string valueQuery_instance;
    if (fromStringValue(preferredLocalityQuery.value(), valueQuery_instance)) {
      preferredLocality = valueQuery_instance;
    }
  }
  std::optional<AccessType> accessType =
      model_from_query_string<AccessType>(request, "access-type");

  auto limitQuery = request.query().get("limit");
  std::optional<int32_t> limit;
  if (limitQuery.has_value()) {
    int32_t valueQuery_instance;
    if (fromStringValue(limitQuery.value(), valueQuery_instance)) {
      limit = valueQuery_instance;
    }
  }
  auto requiredFeaturesQuery = request.query().get("required-features");
  std::optional<std::vector<std::string>> requiredFeatures;
  if (requiredFeaturesQuery.has_value()) {
    std::vector<std::string> valueQuery_instance;
    if (fromStringValue(requiredFeaturesQuery.value(), valueQuery_instance)) {
      requiredFeatures = valueQuery_instance;
    }
  }
  std::optional<ComplexQuery> complexQuery =
      model_from_query_string<ComplexQuery>(request, "complex-query");

  auto maxPayloadSizeQuery = request.query().get("max-payload-size");
  std::optional<int32_t> maxPayloadSize;
  if (maxPayloadSizeQuery.has_value()) {
    int32_t valueQuery_instance;
    if (fromStringValue(maxPayloadSizeQuery.value(), valueQuery_instance)) {
      maxPayloadSize = valueQuery_instance;
    }
  }
  std::optional<AtsssCapability> atsssCapability =
      model_from_query_string<AtsssCapability>(request, "atsss-capability");

  auto upfUeIpAddrIndQuery = request.query().get("upf-ue-ip-addr-ind");
  std::optional<bool> upfUeIpAddrInd;
  if (upfUeIpAddrIndQuery.has_value()) {
    bool valueQuery_instance;
    if (fromStringValue(upfUeIpAddrIndQuery.value(), valueQuery_instance)) {
      upfUeIpAddrInd = valueQuery_instance;
    }
  }

  // Getting the header params
  auto ifNoneMatch = request.headers().tryGetRaw("If-None-Match");

  try {
    this->search_nf_instances(
        targetNfType, requesterNfType, requesterNfInstanceId, serviceNames,
        requesterNfInstanceFqdn, targetPlmnList, requesterPlmnList,
        targetNfInstanceId, targetNfFqdn, hnrfUri, snssais, requesterSnssais,
        plmnSpecificSnssaiList, dnn, nsiList, smfServingArea, tai, amfRegionId,
        amfSetId, guami, supi, ueIpv4Address, ipDomain, ueIpv6Prefix, pgwInd,
        pgw, gpsi, externalGroupIdentity, dataSet, routingIndicator,
        groupIdList, dnaiList, pduSessionTypes, eventIdList, nwdafEventList,
        supportedFeatures, upfIwkEpsInd, chfSupportedPlmn, preferredLocality,
        accessType, limit, requiredFeatures, complexQuery, maxPayloadSize,
        atsssCapability, upfUeIpAddrInd, ifNoneMatch, response);
  } catch (nlohmann::detail::exception& e) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  } catch (Pistache::Http::HttpError& e) {
    response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
    return;
  } catch (std::exception& e) {
    // send a 500 error
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
    return;
  }
}

void DiscNFInstancesStoreApi::nf_instances_store_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

template<class T>
std::optional<T> DiscNFInstancesStoreApi::model_from_query_string(
    const Pistache::Rest::Request& request, const std::string& query_param,
    bool make_json_array) {
  auto query = request.query().get(query_param);
  std::optional<T> ret_optional;
  if (query.has_value()) {
    nlohmann::json j = query.value();
    if (make_json_array) {
      std::string qry_string = query.value();
      std::vector<std::string> split_arr;
      boost::split(
          split_arr, qry_string, boost::is_any_of(","),
          boost::token_compress_on);
      j = split_arr;
    }

    std::cout << "test: " << j.dump() << std::endl;

    T valueQuery_instance;
    nlohmann::from_json(j, valueQuery_instance);
    ret_optional = valueQuery_instance;
  }
  return ret_optional;
}

}  // namespace api
}  // namespace nrf
}  // namespace oai
