/**
 * NRF NFDiscovery Service
 * NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*
 * CompleteStoredSearchDocumentApiImpl.h
 *
 *
 */

#ifndef COMPLETE_STORED_SEARCH_DOCUMENT_API_IMPL_H_
#define COMPLETE_STORED_SEARCH_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <CompleteStoredSearchDocumentApi.h>

#include <pistache/optional.h>

#include "StoredSearchResult.h"
#include "nrf_app.hpp"
#include <string>

namespace oai {
namespace nrf {
namespace api {

using namespace oai::model::nrf;
using namespace oai::nrf::app;

class CompleteStoredSearchDocumentApiImpl
    : public oai::nrf::api::CompleteStoredSearchDocumentApi {
 public:
  CompleteStoredSearchDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, nrf_app* nrf_app_inst,
      std::string address);
  ~CompleteStoredSearchDocumentApiImpl() {}

  void retrieve_complete_search(
      const std::string& searchId, Pistache::Http::ResponseWriter& response);

 private:
  nrf_app* m_nrf_app;
  std::string m_address;
};

}  // namespace api
}  // namespace nrf
}  // namespace oai

#endif
