/**
 * NRF NFDiscovery Service
 * NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "DiscNFInstancesStoreApiImpl.h"
#include <set>
#include "3gpp_29.500.h"
#include "logger.hpp"

namespace oai {
namespace nrf {
namespace api {

using namespace oai::_3gpp::model;
using namespace oai::nrf::app;

DiscNFInstancesStoreApiImpl::DiscNFInstancesStoreApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, nrf_app* nrf_app_inst,
    std::string address)
    : DiscNFInstancesStoreApi(rtr),
      m_nrf_app(nrf_app_inst),
      m_address(address) {}

void DiscNFInstancesStoreApiImpl::search_nf_instances(
    const std::optional<std::string>& targetNfType,
    const std::optional<std::string>& requesterNfType,
    const std::optional<std::string>& requesterNfInstanceId,
    const std::optional<std::vector<ServiceName>>& serviceNames,
    const std::optional<std::string>& requesterNfInstanceFqdn,
    const std::optional<std::vector<PlmnId>>& targetPlmnList,
    const std::optional<std::vector<PlmnId>>& requesterPlmnList,
    const std::optional<std::string>& targetNfInstanceId,
    const std::optional<std::string>& targetNfFqdn,
    const std::optional<std::string>& hnrfUri,
    const std::optional<std::vector<Snssai>>& snssais,
    const std::optional<std::vector<Snssai>>& requesterSnssais,
    const std::optional<std::vector<PlmnSnssai>>& plmnSpecificSnssaiList,
    const std::optional<std::string>& dnn,
    const std::optional<std::vector<std::string>>& nsiList,
    const std::optional<std::string>& smfServingArea,
    const std::optional<Tai>& tai,
    const std::optional<std::string>& amfRegionId,
    const std::optional<std::string>& amfSetId,
    const std::optional<Guami>& guami, const std::optional<std::string>& supi,
    const std::optional<std::string>& ueIpv4Address,
    const std::optional<std::string>& ipDomain,
    const std::optional<Ipv6Prefix>& ueIpv6Prefix,
    const std::optional<bool>& pgwInd, const std::optional<std::string>& pgw,
    const std::optional<std::string>& gpsi,
    const std::optional<std::string>& externalGroupIdentity,
    const std::optional<DataSetId>& dataSet,
    const std::optional<std::string>& routingIndicator,
    const std::optional<std::vector<std::string>>& groupIdList,
    const std::optional<std::vector<std::string>>& dnaiList,
    const std::optional<std::vector<PduSessionType>>& pduSessionTypes,
    const std::optional<std::vector<EventId>>& eventIdList,
    const std::optional<std::vector<NwdafEvent>>& nwdafEventList,
    const std::optional<std::string>& supportedFeatures,
    const std::optional<bool>& upfIwkEpsInd,
    const std::optional<PlmnId>& chfSupportedPlmn,
    const std::optional<std::string>& preferredLocality,
    const std::optional<AccessType>& accessType,
    const std::optional<int32_t>& limit,
    const std::optional<std::vector<std::string>>& requiredFeatures,
    const std::optional<ComplexQuery>& complexQuery,
    const std::optional<int32_t>& maxPayloadSize,
    const std::optional<AtsssCapability>& atsssCapability,
    const std::optional<bool>& upfUeIpAddrInd,
    const std::optional<Pistache::Http::Header::Raw>& ifNoneMatch,
    Pistache::Http::ResponseWriter& response) {
  Logger::nrf_sbi().info(
      "Got a request to discover the set of NF instances that satisfies a "
      "number of input query parameters");

  std::string target_nf_type = {};
  if (targetNfType.has_value()) {
    target_nf_type = targetNfType.value();
    Logger::nrf_sbi().debug("\tTarget NF type:  %s", target_nf_type.c_str());
  }

  std::string requester_nf_type = {};
  if (requesterNfType.has_value()) {
    requester_nf_type = requesterNfType.value();
    Logger::nrf_sbi().debug(
        "\tRequested NF type:  %s", requester_nf_type.c_str());
  }

  std::string requester_nf_instance_id = {};
  if (requesterNfInstanceId.has_value()) {
    requester_nf_instance_id = requesterNfInstanceId.value();
    Logger::nrf_sbi().debug(
        "\tRequested NF instance id:  %s", requester_nf_instance_id.c_str());
  }

  uint32_t limit_nfs = 0;
  if (limit.has_value()) {
    limit_nfs = limit.value();
    Logger::nrf_sbi().debug(
        "\tMaximum number of NFProfiles to be returned in the response: %d",
        limit_nfs);
  }

  // TODO: other query parameters

  int http_code                  = 0;
  ProblemDetails problem_details = {};
  std::string search_id          = {};
  m_nrf_app->handle_search_nf_instances(
      target_nf_type, requester_nf_type, requester_nf_instance_id, limit_nfs,
      search_id, http_code, 1, problem_details);

  nlohmann::json json_data = {};
  std::string content_type = "application/json";

  std::shared_ptr<nrf_search_result> search_result = {};
  m_nrf_app->find_search_result(search_id, search_result);

  if (http_code != oai::common::sbi::http_status_code::OK) {
    to_json(json_data, problem_details);
    content_type = "application/problem+json";
  } else {
    // convert the profile to Json
    if (search_result != nullptr)
      search_result.get()->to_json(json_data, limit_nfs);
  }

  // TODO: applying client restrictions in terms of the number of
  // instances to be returned (i.e. "limit" or "max-
  // payload-size" query parameters) .

  Logger::nrf_sbi().debug("Json data: %s", json_data.dump().c_str());

  // content type
  response.headers().add<Pistache::Http::Header::ContentType>(
      Pistache::Http::Mime::MediaType(content_type));
  // TODO: add headers:  Cache-Control, ETag

  response.send(Pistache::Http::Code(http_code), json_data.dump().c_str());
}

}  // namespace api
}  // namespace nrf
}  // namespace oai
