/**
 * NRF NFDiscovery Service
 * NRF NFDiscovery Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*
 * NFInstancesStoreApiImpl.h
 *
 *
 */

#ifndef DISC_NF_INSTANCES_STORE_API_IMPL_H_
#define DISC_NF_INSTANCES_STORE_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <DiscNFInstancesStoreApi.h>

#include <optional>

#include "AccessType.h"
#include "AtsssCapability.h"
#include "ComplexQuery.h"
#include "DataSetId.h"
#include "EventId.h"
#include "Guami.h"
#include "Ipv6Prefix.h"
#include "NFType.h"
#include "NwdafEvent.h"
#include "PduSessionType.h"
#include "PlmnId.h"
#include "PlmnSnssai.h"
#include "ProblemDetails.h"
#include "SearchResult.h"
#include "ServiceName.h"
#include "Snssai.h"
#include "Tai.h"
#include "nrf_app.hpp"
#include <string>
#include <set>

namespace oai {
namespace nrf {
namespace api {

using namespace oai::_3gpp::model;
using namespace oai::nrf::app;

class DiscNFInstancesStoreApiImpl
    : public oai::nrf::api::DiscNFInstancesStoreApi {
 public:
  DiscNFInstancesStoreApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, nrf_app* nrf_app_inst,
      std::string address);
  ~DiscNFInstancesStoreApiImpl() {}

  void search_nf_instances(
      const std::optional<std::string>& targetNfType,
      const std::optional<std::string>& requesterNfType,
      const std::optional<std::string>& requesterNfInstanceId,
      const std::optional<std::vector<ServiceName>>& serviceNames,
      const std::optional<std::string>& requesterNfInstanceFqdn,
      const std::optional<std::vector<oai::_3gpp::model::PlmnId>>&
          targetPlmnList,
      const std::optional<std::vector<oai::_3gpp::model::PlmnId>>&
          requesterPlmnList,
      const std::optional<std::string>& targetNfInstanceId,
      const std::optional<std::string>& targetNfFqdn,
      const std::optional<std::string>& hnrfUri,
      const std::optional<std::vector<oai::_3gpp::model::Snssai>>& snssais,
      const std::optional<std::vector<oai::_3gpp::model::Snssai>>&
          requesterSnssais,
      const std::optional<std::vector<PlmnSnssai>>& plmnSpecificSnssaiList,
      const std::optional<std::string>& dnn,
      const std::optional<std::vector<std::string>>& nsiList,
      const std::optional<std::string>& smfServingArea,
      const std::optional<oai::_3gpp::model::Tai>& tai,
      const std::optional<std::string>& amfRegionId,
      const std::optional<std::string>& amfSetId,
      const std::optional<oai::_3gpp::model::Guami>& guami,
      const std::optional<std::string>& supi,
      const std::optional<std::string>& ueIpv4Address,
      const std::optional<std::string>& ipDomain,
      const std::optional<oai::_3gpp::model::Ipv6Prefix>& ueIpv6Prefix,
      const std::optional<bool>& pgwInd, const std::optional<std::string>& pgw,
      const std::optional<std::string>& gpsi,
      const std::optional<std::string>& externalGroupIdentity,
      const std::optional<DataSetId>& dataSet,
      const std::optional<std::string>& routingIndicator,
      const std::optional<std::vector<std::string>>& groupIdList,
      const std::optional<std::vector<std::string>>& dnaiList,
      const std::optional<std::vector<oai::_3gpp::model::PduSessionType>>&
          pduSessionTypes,
      const std::optional<std::vector<EventId>>& eventIdList,
      const std::optional<std::vector<NwdafEvent>>& nwdafEventList,
      const std::optional<std::string>& supportedFeatures,
      const std::optional<bool>& upfIwkEpsInd,
      const std::optional<oai::_3gpp::model::PlmnId>& chfSupportedPlmn,
      const std::optional<std::string>& preferredLocality,
      const std::optional<oai::_3gpp::model::AccessType>& accessType,
      const std::optional<int32_t>& limit,
      const std::optional<std::vector<std::string>>& requiredFeatures,
      const std::optional<oai::_3gpp::model::ComplexQuery>& complexQuery,
      const std::optional<int32_t>& maxPayloadSize,
      const std::optional<oai::_3gpp::model::AtsssCapability>& atsssCapability,
      const std::optional<bool>& upfUeIpAddrInd,
      const std::optional<Pistache::Http::Header::Raw>& ifNoneMatch,
      Pistache::Http::ResponseWriter& response);

 private:
  nrf_app* m_nrf_app;
  std::string m_address;
};

}  // namespace api
}  // namespace nrf
}  // namespace oai

#endif
